### Create/ Add new user
POST http://localhost:3000/api/v1/users
Content-Type: application/json

{
    "name":{
        "first": "Noa2",
        "middle": "",
        "last": "Noai2"
    },
    "address":{
        "street": "test1",
        "city": "test1",
        "country": "test1",
        "state": "test1",
        "houseNumber": 10,
        "zip": "12345"
    },
    "image":{
        "alt": "user-profile",
        "url": "https://picsum.photos/200/300"
    },
    "phone": "0524720544",
    "email": "n2@n.com",
    "isBusiness": true,
    "password": "Aa123456!"
}

### Get All Users
GET http://localhost:3000/api/v1/users